[loggers]
keys=root

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=simpleFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler,fileHandler

[handler_consoleHandler]
class=StreamHandler
formatter=simpleFormatter
level=INFO

[handler_fileHandler]
class=FileHandler
formatter=simpleFormatter
level=DEBUG
args=("C:\\Users\\swath\\githubrepocreation\\log\\app2.log", "a", "utf-8")

[formatter_simpleFormatter]
format=%(asctime)s - %(levelname)s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S
